

- name: postgres | install pgbouncer
  ansible.builtin.apt:
    update_cache: yes
    pkg:
     - "pgbouncer"

- name: pgbouncer | config directory
  ansible.builtin.file:
    path: "/etc/pgbouncer/"
    state: directory
    owner: postgres
    group: postgres

- name: postgres |  copy config
  ansible.builtin.copy:
    src: '{{item}}'
    dest: '/etc/pgbouncer/{{item}}'
    owner: postgres
    group: postgres
  loop:
    - 'pgbouncer.ini'


- name: pgbouncer | generate hash users pgbouncer
  ansible.builtin.shell: PGPASSWORD="{{ postgres_super }}" psql -Atq -U postgres -d postgres -c "SELECT concat('\"', usename, '\" \"', passwd, '\"') FROM pg_shadow" -h {{ ansible_default_ipv4.address }} > /etc/pgbouncer/userlist.txt

- name: pgbouncer | set owner
  ansible.builtin.file:
    path: /etc/pgbouncer/userlist.txt
    owner: postgres
    group: postgres



- name: pgbouncer restart
  ansible.builtin.service:
    name: pgbouncer
    state: restarted
