- name: prometheus install packages
  ansible.builtin.apt:
    update_cache: yes
    pkg:
     - "nginx"
     - "curl"
     - "mc"
     - "jq"


- name: nginx del default config
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: nginx enable
  systemd: name="nginx" daemon_reload=yes enabled=yes

- name: nginx start
  ansible.builtin.service:
    name: nginx
    state: restarted

#создаём группу для prometheus
- name: create group prometheus
  ansible.builtin.group:
    name: prometheus
    state: present

#создаём юзера для prometheus
- name: create prometheus users
  ansible.builtin.user:
    name: prometheus
    shell: /bin/false
    groups: prometheus
    append: no
    password: "$y$j9T$lXUEtuHIWUMKoYt6JebHT1$zikw9hpSqtZNM.RIYl5Sa..mySiVKjsxNMUCFdpL3z0"
    update_password: always
    create_home: no

#создаём директории для ПО
- name: create prometheus dirs
  ansible.builtin.file:
    path: "{{item}}"
    state: directory
    owner: prometheus
    group: prometheus
  loop:
   - "/var/lib/prometheus"
   - "/etc/prometheus"
   - "/etc/prometheus/rules"
   - "/etc/prometheus/rules.d"
   - "/etc/prometheus/files_sd"

#- name: node exporter download
#  ansible.builtin.shell:
#    cmd: wget "https://github.com/prometheus/prometheus/releases/download/v2.46.0/prometheus-2.46.0.linux-amd64.tar.gz" -O prometheus.tar.gz && tar -xzvf prometheus.tar.gz --directory=/usr/local/sbin/ && rm prometheus.tar.gz
#    chdir: /usr/local/sbin/

- name: prometheus add path
  copy:
    dest: /etc/profile.d/prometheus-path.sh
    content: 'PATH=$PATH:/usr/local/sbin/prometheus-2.46.0.linux-amd64'

- name: prometheus copy configs
  ansible.builtin.copy:
    src: "prometheus/{{item}}"
    dest: "/etc/prometheus/{{item}}"
    owner: prometheus
    group: prometheus
  loop:
   - "prometheus.yml"
   - "console_libraries/."
   - "consoles/."

- name: prometheus copy service
  copy:
    src: "prometheus/prometheus.service"
    dest: "/etc/systemd/system/prometheus.service"

- name: prometheus enable
  systemd: name="prometheus" daemon_reload=yes enabled=yes

- name: prometheus start
  ansible.builtin.service:
    name: prometheus
    state: restarted

