- name: grafana install packages
  ansible.builtin.apt:
    update_cache: yes
    pkg:
     - "apt-transport-https"
     - "software-properties-common"


- name: grafana | download deb
  ansible.builtin.shell:
    cmd: wget https://dl.grafana.com/oss/release/grafana_10.0.3_amd64.deb -O /tmp/grafana.deb
    chdir: /tmp

#- name: grafana | install deb
#  ansible.builtin.shell:
#    cmd: sudo dpkg -i /tmp/grafana.deb


- name: prometheus copy configs
  ansible.builtin.copy:
    src: "grafana/prom-datasource.yml"
    dest: "/etc/grafana/provisioning/datasources/prom-datasource.yml"
    owner: root
    group: grafana

- name: grafana enable
  systemd: name="grafana-server" daemon_reload=yes enabled=yes

- name: grafana start
  ansible.builtin.service:
    name: grafana-server
    state: restarted

