- name: grafana install packages
  ansible.builtin.apt:
    update_cache: yes
    pkg:
     - "apt-transport-https"
     - "software-properties-common"


- name: grafana | download deb
  ansible.builtin.shell:
    cmd: wget https://dl.grafana.com/oss/release/grafana_10.0.3_amd64.deb -O /tmp/grafana.deb
    chdir: /tmp

- name: grafana | install deb
  ansible.builtin.shell:
    cmd: sudo dpkg -i /tmp/grafana.deb


- name: create dashboard dirs
  ansible.builtin.file:
    path: "{{item}}"
    state: directory
    owner: grafana
    group: grafana
  loop:
   - "/var/lib/grafana/dashboards"
   - "/var/lib/grafana/dashboards/os"
   - "/var/lib/grafana/dashboards/postgresql"


- name: grafana copy promesheus datasource
  ansible.builtin.copy:
    src: "grafana/prom-datasource.yml"
    dest: "/etc/grafana/provisioning/datasources/prom-datasource.yml"
    owner: root
    group: grafana


- name: grafana copy dashboards config
  ansible.builtin.copy:
    src: "grafana/{{item}}"
    dest: "/etc/grafana/provisioning/dashboards/{{item}}"
    owner: root
    group: grafana
  loop:
   - "os_dashboadrs.yml"
   - "postgresql_dashboadrs.yml"


# node-exporter https://grafana.com/grafana/dashboards/1860-node-exporter-full/
# postgres-exporter https://grafana.com/grafana/dashboards/9628-postgresql-database/
# pgbouncer-exporer https://grafana.com/grafana/dashboards/9760-postgresql-pgbouncer/

- name: grafana copy dashboards config
  ansible.builtin.copy:
    src: "grafana/{{item}}"
    dest: "/var/lib/grafana/dashboards/{{item}}"
    owner: root
    group: grafana
  loop:
   - "os/node-exporter.json"
   - "postgresql/pg-database.json"
   - "postgresql/pgbouncer_exporter.json"
   - "postgresql/pg-full.json"


- name: grafana enable
  systemd: name="grafana-server" daemon_reload=yes enabled=yes

- name: grafana start
  ansible.builtin.service:
    name: grafana-server
    state: restarted

