#ставим пакеты unbound и сопутствующие
- name: install packages
  ansible.builtin.apt:
    update_cache: yes
    pkg:
     - "unzip"

#создаём директории для ПО
- name: create dirs
  ansible.builtin.file:
    path: "{{item}}"
    state: directory
  loop:
   - "/usr/local/sbin/postgres_exporter"


- name: postgres_exporter | get export
  ansible.builtin.unarchive:
    src: https://github.com/aoslepov/pgdb_teach/blob/main/project/yc/ROLES/EXPORTERS/files/postgres_exporter.tar.gz
    dest: /usr/local/sbin/postgres_exporter
    remote_src: yes



