- name: install packages
  ansible.builtin.apt:
    update_cache: yes
    pkg:
     - "unzip"

- name: postgres exporter create dirs
  ansible.builtin.file:
    path: "{{item}}"
    state: directory
  loop:
   - "/usr/local/sbin/postgresql_exporter"

- name: postgres_exporter templating service
  template:
    src: "postgres_exporter.service"
    dest: "/etc/systemd/system/postgres_exporter.service"

- name: download postgres exporter
  ansible.builtin.unarchive:
    src: postgres_exporter.tar.gz
    dest: /usr/local/sbin/postgresql_exporter/
 
#перегружаем конфигурацию systemd 
- name: postgres_exporter enable 
  systemd: name="postgres_exporter" daemon_reload=yes enabled=yes

# запускаем сервис
- name: postgres_exporter start
  ansible.builtin.service:
    name: postgres_exporter
    state: restarted
