{
 "title": "PostgreSQL PGbouncer",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(pgbouncer_up, instance)"
   },
   {
    "name": "port",
    "query": "label_values(pgbouncer_up, instance)"
   },
   { "name": "hostname", "label": "Hostname", "query": { "query": "query_result(pgbouncer_up)" } },
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Client active connections ",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum (pgbouncer_pools_client_active_connections{instance=~\"$hostname\"})"
    }
   ]
  },
  {
   "title": "Stats queries total ",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum ( rate(pgbouncer_stats_queries_pooled_total{instance=~\"$hostname\"}[1m]) )  "
    }
   ]
  },
  {
   "title": "Database pool size.",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (pgbouncer_databases_pool_size{instance=~\"$hostname\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Databases database reserve pool size.",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (pgbouncer_databases_reserve_pool{instance=~\"$hostname\"}) ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Query Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "sort_desc( sum by (instance) ( rate(pgbouncer_stats_queries_duration_seconds_total{instance=~\"$hostname\"}[1m]) ) ) ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Stats queries",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sort_desc( sum by (instance) ( rate(pgbouncer_stats_queries_duration_seconds_total{instance=~\"$hostname\"}[1m]) ) )",
     "legendFormat": "{{ instance }}: Stats queries duration microseconds"
    },
    {
     "expr": "sort_desc( sum by (instance) ( rate(pgbouncer_stats_client_wait_seconds_total{instance=~\"$hostname\"}[1m]) ) )  ",
     "legendFormat": "{{instance}}: Stats waiting duration microseconds"
    }
   ]
  },
  {
   "title": "Transactions stats",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sort_desc( sum by (instance) ( rate(pgbouncer_stats_queries_duration_seconds_total{instance=~\"$hostname\"}[1m]) ) )  ",
     "legendFormat": "{{ instance }}: Stats transactions duration microseconds"
    },
    {
     "expr": "sort_desc( sum by (instance) ( rate(pgbouncer_stats_sql_transactions_pooled_total{instance=~\"$hostname\"}[1m]) ) ) ",
     "legendFormat": "{{ instance }}: Stats transactions total"
    }
   ]
  },
  {
   "title": "Pgbouncer pools connections",
   "type": "graph",
   "description": " ",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(pgbouncer_pools_client_active_connections{instance=~\"$hostname\"})",
     "legendFormat": "{{instance}}: Client active connections "
    },
    {
     "expr": "sum by (instance) (pgbouncer_stats_client_wait_seconds_total{instance=~\"$hostname\"})",
     "legendFormat": "{{instance}}: Client waiting connections"
    },
    {
     "expr": "sum by (instance) (pgbouncer_pools_server_active_connections{database=~\"$db\", instance=~\"$hostname\"})",
     "legendFormat": "{{instance}}: Server active connections"
    },
    {
     "expr": "sum by (instance) (pgbouncer_pools_server_idle_connections{instance=~\"$hostname\"})",
     "legendFormat": "{{instance}}: Server idle connections"
    },
    {
     "expr": "sum by (instance) (pgbouncer_pools_server_used_connections{instance=~\"$hostname\"})",
     "legendFormat": "{{instance}}: Server used connections"
    },
    {
     "expr": "sum by (instance) (pgbouncer_pools_server_testing_connections{instance=~\"$hostname\"})",
     "legendFormat": "{{instance}}: Server testing connections"
    },
    {
     "expr": "sum by (instance) (pgbouncer_pools_server_login_connections{instance=~\"$hostname\"})",
     "legendFormat": "{{instance}}: Server login connections"
    },
    {
     "expr": "sum by (instance) (pgbouncer_databases_database_current_connections{instance=~\"$hostname\"})",
     "legendFormat": "{{instance}}: Database current connections"
    }
   ]
  },
  {
   "title": "Total of incoming / outgoing bytes ",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc( sum by (instance) ( rate(pgbouncer_stats_received_bytes_total{instance=~\"$hostname\"}[1m])*8 ) ) ",
     "legendFormat": "{{ instance }}: Stats received bytes total"
    },
    {
     "expr": "sort_desc( sum by (instance) ( rate(pgbouncer_stats_sent_bytes_total{instance=~\"$hostname\"}[1m])*8 ) )",
     "legendFormat": "{{ instance }}: Stats sent bytes total"
    }
   ]
  }
 ]
}