# # config file version
apiVersion: 1

providers:
 - name: 'postgresql'
   orgId: 1
   folder: 'postgresql'
   folderUid: 'e4b9d066-311d-11ee-99d5-57fe2e0c8c4e'
   type: file
   options:
     path: /var/lib/grafana/dashboards/postgresql
